# Generated by Django 3.2.4 on 2021-06-16 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
