# Generated by Django 3.2.4 on 2021-06-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210616_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Edition',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
